global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'catalog_service'
    static_configs:
      - targets: ['host.docker.internal:8000']

  - job_name: 'order_service'
    static_configs:
      - targets: ['host.docker.internal:9000']

  - job_name: 'payment_service'
    static_configs:
      - targets: ['host.docker.internal:6002']

  - job_name: 'user_service'
    static_configs:
      - targets: ['host.docker.internal:6000']
